/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shinsengumifinance;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class JFConfig extends javax.swing.JFrame {

    Finance fin;
    JFFinance jffinance;
    String bdpath;
    
    public JFConfig(Finance fin, JFFinance jffinance, String bdpath) {        
        this.bdpath = bdpath;
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);
        initComponents();
        this.fin = fin;
        this.jffinance = jffinance;
        //setIconImage(new javax.swing.ImageIcon(getClass().getResource("/shinsengumifinance/img/Beri_128x81.fw.png")).getImage());
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("img/Beri_128x81.fw.png")).getImage());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Config");
        setAlwaysOnTop(true);

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset Database");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Are you sure?", "Atention", JOptionPane.YES_NO_OPTION);
        if (op == 0) {
            String xml = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" standalone=\"no\"?>\n" +
                         "<root>\n" +
                         "    <name>default</name>\n" +
                         "    <balance>0</balance>\n" +
                         "    <in></in>   \n" +
                         "    <out></out>\n" +
                         "</root>";
            File bd = new File(bdpath);
            FileWriter fileWriter = null;
            try {
                fileWriter = new FileWriter(bd);
                fileWriter.write(xml);
            } catch (IOException ex) {
                Logger.getLogger(JFConfig.class.getName()).log(Level.SEVERE, null, ex);
            }            
            try {
                fileWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(JFConfig.class.getName()).log(Level.SEVERE, null, ex);
            }
            jffinance.reset_finance();
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
