/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shinsengumifinance;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vinicius
 */
public final class JFFinance extends javax.swing.JFrame {

    Finance fin;
    private final String bdpath = "bd/default.xml"; //"src/shinsengumifinance/bd/default.xml"
            
    public JFFinance() {        
        String data, hora;  
        Date agora = new java.util.Date();;  
        SimpleDateFormat formata = new SimpleDateFormat("ddMMyyyy");  
        data = formata.format(agora);  
        formata = new SimpleDateFormat("hhmmss");  
        hora = formata.format(agora);  
        System.out.println(data);  
        System.out.println(hora);  
        backup(bdpath, bdpath + "." + data + "-" + hora + ".bkp");
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);
        initComponents();
        fin = new Finance(bdpath); 
        getContentPane().setBackground(Color.white); //deixar o frame branco
        //setIconImage(new javax.swing.ImageIcon(getClass().getResource("/shinsengumifinance/img/Beri_128x81.fw.png")).getImage());
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("img/Beri_128x81.fw.png")).getImage());
        update_balance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpButtons = new javax.swing.JPanel();
        jbDeposit = new javax.swing.JButton();
        jbWithdraw = new javax.swing.JButton();
        jbReport = new javax.swing.JButton();
        jbMembers = new javax.swing.JButton();
        jpBalance = new javax.swing.JPanel();
        jlBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shinsengumi Finance");

        jpButtons.setBackground(new java.awt.Color(255, 255, 255));
        jpButtons.setFocusable(false);

        jbDeposit.setBackground(new java.awt.Color(51, 204, 255));
        jbDeposit.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbDeposit.setForeground(new java.awt.Color(255, 255, 255));
        jbDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shinsengumifinance/img/nami.png"))); // NOI18N
        jbDeposit.setText("Deposit");
        jbDeposit.setToolTipText("");
        jbDeposit.setBorder(null);
        jbDeposit.setContentAreaFilled(false);
        jbDeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbDeposit.setOpaque(true);
        jbDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDepositActionPerformed(evt);
            }
        });

        jbWithdraw.setBackground(new java.awt.Color(51, 204, 255));
        jbWithdraw.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbWithdraw.setForeground(new java.awt.Color(255, 255, 255));
        jbWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shinsengumifinance/img/luffy.png"))); // NOI18N
        jbWithdraw.setText("Withdraw");
        jbWithdraw.setBorder(null);
        jbWithdraw.setContentAreaFilled(false);
        jbWithdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbWithdraw.setOpaque(true);
        jbWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbWithdrawActionPerformed(evt);
            }
        });

        jbReport.setBackground(new java.awt.Color(51, 204, 255));
        jbReport.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbReport.setForeground(new java.awt.Color(255, 255, 255));
        jbReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shinsengumifinance/img/sanji.png"))); // NOI18N
        jbReport.setText("Report");
        jbReport.setBorder(null);
        jbReport.setContentAreaFilled(false);
        jbReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbReport.setOpaque(true);
        jbReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReportActionPerformed(evt);
            }
        });

        jbMembers.setBackground(new java.awt.Color(51, 204, 255));
        jbMembers.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbMembers.setForeground(new java.awt.Color(255, 255, 255));
        jbMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shinsengumifinance/img/chopper.png"))); // NOI18N
        jbMembers.setText("config");
        jbMembers.setBorder(null);
        jbMembers.setContentAreaFilled(false);
        jbMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMembers.setOpaque(true);
        jbMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMembersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonsLayout = new javax.swing.GroupLayout(jpButtons);
        jpButtons.setLayout(jpButtonsLayout);
        jpButtonsLayout.setHorizontalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbDeposit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jbMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpButtonsLayout.setVerticalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jbDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbReport, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jbMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpBalance.setBackground(new java.awt.Color(255, 255, 255));

        jlBalance.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jlBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpBalanceLayout = new javax.swing.GroupLayout(jpBalance);
        jpBalance.setLayout(jpBalanceLayout);
        jpBalanceLayout.setHorizontalGroup(
            jpBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpBalanceLayout.setVerticalGroup(
            jpBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDepositActionPerformed
        new JFOperation("Deposit", fin, this);
    }//GEN-LAST:event_jbDepositActionPerformed

    private void jbWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbWithdrawActionPerformed
        new JFOperation("Withdraw", fin, this);
    }//GEN-LAST:event_jbWithdrawActionPerformed

    private void jbMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMembersActionPerformed
        new JFConfig(fin, this, bdpath);
    }//GEN-LAST:event_jbMembersActionPerformed

    private void jbReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReportActionPerformed
        new JFReport(fin);
    }//GEN-LAST:event_jbReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFinance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFinance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFinance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFinance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFinance().setVisible(true);
            }
        });
    }
    
    public void update_balance(){
        NumberFormat numberFormater = NumberFormat.getCurrencyInstance();
        this.jlBalance.setText("Balance: " + numberFormater.format(Float.parseFloat(fin.balance())));
    }
    
    public void reset_finance(){
        fin = new Finance(bdpath);
        update_balance();
    }
    
    private void backup(String src, String dst){
        File fsrc = new File(src);
        File fdst = new File(dst);
        OutputStream out = null;
        try (InputStream in = new FileInputStream(fsrc)) {
            out = new FileOutputStream(fdst);
            byte[] buf = new byte[1024];
            int len;
            while ((len = in.read(buf)) > 0) {
                out.write(buf, 0, len);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFFinance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFFinance.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(JFFinance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbDeposit;
    private javax.swing.JButton jbMembers;
    private javax.swing.JButton jbReport;
    private javax.swing.JButton jbWithdraw;
    private javax.swing.JLabel jlBalance;
    private javax.swing.JPanel jpBalance;
    private javax.swing.JPanel jpButtons;
    // End of variables declaration//GEN-END:variables
}
