/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shinsengumifinance;

import java.text.NumberFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public final class JFReport extends javax.swing.JFrame{

    Finance fin;
    
    public JFReport(Finance fin) {
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);
        initComponents();
        this.fin = fin;
        //this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/shinsengumifinance/img/Beri_128x81.fw.png")).getImage());
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("img/Beri_128x81.fw.png")).getImage());
        get_deposits();
        get_withdraws();
        setVisible(true);
    }
    
    public void get_deposits(){
        String[][] deposits;
        float total = 0;
        deposits = fin.deposits();
        DefaultTableModel model = (DefaultTableModel) jtDeposits.getModel();
        for (String[] deposit : deposits) {
            model.addRow(new Object[]{deposit[0],deposit[1],"R$ " + deposit[2]});
            total += Float.parseFloat(deposit[2]);
        }
        NumberFormat numberFormater = NumberFormat.getCurrencyInstance();
        this.jlDTotal.setText("Total: " + numberFormater.format(total));
    }
    
    public void get_withdraws(){
        String[][] withdraws;
        float total = 0;
        withdraws = fin.withdraws();
        DefaultTableModel model = (DefaultTableModel) jtWithdraws.getModel();
        for (String[] withdraw : withdraws) {
            model.addRow(new Object[]{withdraw[0],withdraw[1],"R$ " + withdraw[2]});
            total += Float.parseFloat(withdraw[2]);
        }
        NumberFormat numberFormater = NumberFormat.getCurrencyInstance();
        this.jlWTotal.setText("Total: " + numberFormater.format(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDeposits = new javax.swing.JTable();
        jlDTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtWithdraws = new javax.swing.JTable();
        jlWTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report");

        jTabbedPane1.setBackground(new java.awt.Color(51, 204, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setForeground(new java.awt.Color(51, 204, 255));

        jtDeposits.setBackground(new java.awt.Color(51, 204, 255));
        jtDeposits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtDeposits.setForeground(new java.awt.Color(255, 255, 255));
        jtDeposits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Description", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtDeposits);

        jlDTotal.setBackground(new java.awt.Color(51, 204, 255));
        jlDTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlDTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDTotal.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
            .addComponent(jlDTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Deposits", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setForeground(new java.awt.Color(51, 204, 255));

        jtWithdraws.setBackground(new java.awt.Color(51, 204, 255));
        jtWithdraws.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtWithdraws.setForeground(new java.awt.Color(255, 255, 255));
        jtWithdraws.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Description", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtWithdraws);

        jlWTotal.setBackground(new java.awt.Color(51, 204, 255));
        jlWTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlWTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlWTotal.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
            .addComponent(jlWTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlWTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Withdraws", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlDTotal;
    private javax.swing.JLabel jlWTotal;
    private javax.swing.JTable jtDeposits;
    private javax.swing.JTable jtWithdraws;
    // End of variables declaration//GEN-END:variables
}
